services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container thomas/src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    # environment:
    # if you use window this options must be set
    # - CHOKIDAR_USEPOLLING=true
    ports:
      # your application listen port
      - 3000:3000
      # debugging port
      - 9229:9229
